version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: kanastra
            DB_USERNAME: kanastra
            DB_PASSWORD: kanastra
        depends_on:
            - redis
        networks:
            - kanastra-network

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - kanastra-network

    mysql:
        image: mysql:5.7
        container_name: kanastra-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: kanastra
            MYSQL_USER: kanastra
            MYSQL_PASSWORD: kanastra
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - kanastra-network

    # queue
    queue:
        image: especializati/laravel9-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - kanastra-network

    # redis
    redis:
        image: redis:latest
        networks:
            - kanastra-network

networks:
    kanastra-network:
        driver: bridge
